sudo: required

services:
  - docker

before_install:
  - docker build -t franciscoserrano/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true franciscoserrano/docker-react npm run test